version: '3.8'

services:
  # api:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   # command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: teebaker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
